// app/layout.tsx
import { AppProviders } from '@/shared/providers';
import { pretendard, suite } from '@/shared/lib/font';
import '@/shared/styles/globals.css';
import type { Metadata } from 'next';
import GlobalChrome from '@/shared/components/odos-ui/global-chrome';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} ${suite.variable} font-pretendard bg-gray-50 text-gray-900`}
      >
        <AppProviders>
          <GlobalChrome />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
