// app/layout.tsx
import { AppProviders } from '@/shared/providers';
import { pretendard, suite } from '@/shared/lib/font';
import '@/shared/styles/globals.css';
import type { Metadata, Viewport } from 'next';
import GlobalChromeWrapper from '@/components/global-chrome-wrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} ${suite.variable} font-pretendard bg-gray-50 text-gray-900`}
      >
        <AppProviders>
          <GlobalChromeWrapper />
          <div style={{ position: 'relative', minHeight: '100vh' }}>{children}</div>
        </AppProviders>
      </body>
    </html>
  );
}
