import { AppProviders } from '@/providers';
import type { Metadata } from 'next';
import { pretendard, suite } from '@/lib/font';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en">
      <AppProviders>
        <body className={`${pretendard.variable} ${suite.variable} font-pretendard`}>
          {children}
        </body>
      </AppProviders>
    </html>
  );
}
