import { Notification } from '../type/notification';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    category: 'FRIEND',
    type: 'FRIEND_REQUEST',
    message: '김철수님이 친구 신청을 보냈어요.',
    targetType: 'MEMBER',
    targetId: 101,
    isRead: false,
    groupedCount: 1,
    actorId: 101,
    actorNickname: '김철수',
    actorProfileUrl: null,
    createdAt: '2026-04-26T10:30:00Z',
  },
  {
    id: 2,
    category: 'FRIEND',
    type: 'FRIEND_ACCEPT',
    message: '이영희님이 친구 신청을 수락했습니다.',
    targetType: 'MEMBER',
    targetId: 102,
    isRead: false,
    groupedCount: 1,
    actorId: 102,
    actorNickname: '이영희',
    actorProfileUrl: null,
    createdAt: '2026-04-26T09:15:00Z',
  },
  {
    id: 3,
    category: 'DIARY',
    type: 'DIARY_COMMENT',
    message: '최수진님이 댓글을 달았습니다.',
    targetType: 'DIARY',
    targetId: 302,
    isRead: true,
    groupedCount: 1,
    actorId: 104,
    actorNickname: '최수진',
    actorProfileUrl: null,
    createdAt: '2026-04-25T14:22:00Z',
  },
  {
    id: 4,
    category: 'CHALLENGE',
    type: 'CHALLENGE_APPROVED',
    message: '[30일 러닝 챌린지] 챌린지원이 되었습니다!',
    targetType: 'CHALLENGE',
    targetId: 201,
    isRead: true,
    groupedCount: 1,
    actorId: null,
    actorNickname: null,
    actorProfileUrl: null,
    createdAt: '2026-04-24T09:00:00Z',
  },
];
