import { Notification } from '../type/notification';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    type: 'FRIEND_REQUEST',
    message: '김철수님이 친구 신청을 보냈어요.',
    isRead: false,
    createdAt: '2026-04-26T10:30:00Z',
    actionUrl: '/profile/101',
    sender: {
      id: 101,
      nickname: '김철수',
      profileImage: null,
    },
  },
  {
    id: 2,
    type: 'FRIEND_ACCEPT',
    message: '이영희님이 친구 신청을 수락했습니다. 이제 일지를 확인해보세요!',
    isRead: false,
    createdAt: '2026-04-26T09:15:00Z',
    actionUrl: '/profile/102',
    sender: {
      id: 102,
      nickname: '이영희',
      profileImage: null,
    },
  },
  {
    id: 3,
    type: 'DIARY_POST',
    message: '박민준님이 일지를 등록했어요: 오늘의 러닝 기록',
    isRead: true,
    createdAt: '2026-04-25T18:00:00Z',
    actionUrl: '/diary/301',
    sender: {
      id: 103,
      nickname: '박민준',
      profileImage: null,
    },
  },
  {
    id: 4,
    type: 'DIARY_COMMENT',
    message: '최수진님이 댓글을 달았습니다: 오늘도 고생했어요!',
    isRead: true,
    createdAt: '2026-04-25T14:22:00Z',
    actionUrl: '/diary/302',
    sender: {
      id: 104,
      nickname: '최수진',
      profileImage: null,
    },
  },
  {
    id: 5,
    type: 'COMMENT_REPLY',
    message: '정다은님이 내 댓글에 답글을 남겼습니다: 맞아요, 저도 그렇게 생각해요',
    isRead: true,
    createdAt: '2026-04-25T11:05:00Z',
    actionUrl: '/diary/303',
    sender: {
      id: 105,
      nickname: '정다은',
      profileImage: null,
    },
  },
  {
    id: 6,
    type: 'LIKE_MILESTONE',
    message: '작성하신 일지의 좋아요가 10개를 넘어갔어요! 🎉',
    isRead: false,
    createdAt: '2026-04-24T20:00:00Z',
    actionUrl: '/diary/304',
    sender: null,
  },
  {
    id: 7,
    type: 'CHALLENGE_APPROVED',
    message: '[30일 러닝 챌린지] 챌린지원이 되었습니다! 열심히 참여해봐요!',
    isRead: true,
    createdAt: '2026-04-24T09:00:00Z',
    actionUrl: '/challenge/201',
    sender: null,
  },
  {
    id: 8,
    type: 'CHALLENGE_REJECTED',
    message: '[독서 마라톤] 챌린지 참가가 거절되었습니다.',
    isRead: true,
    createdAt: '2026-04-23T16:30:00Z',
    actionUrl: '/',
    sender: null,
  },
];
